version: "3.8"

services:
  nodejs:
    build: .
    container_name: transaction-history
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/transactionhistory
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nodejs

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=shivangigarg678@gmail.com
      - GF_SMTP_PASSWORD=neyi wfcp yoei gbpy
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=shivangigarg678@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alerts
    depends_on:
      - prometheus

